name: Check Markdown links

on: pull_request

jobs:
  markdown-link-check:
    name: 'Pull request check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Lint check'
        uses: gaurav-nelson/github-action-markdown-link-check@v1
